---
language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libx11-dev libxt-dev libraw1394-dev libavc1394-dev libiec61883-dev libfreetype6-dev yasm autoconf libtool build-essential jhead
  - sudo apt-get install -qq libaudio-dev libpulse-dev libasound-dev
jdk:
  - oraclejdk8
script:
  - export JDK_HOME=$JAVA_HOME
  - cd build
  - ./buildsage.sh || { echo "Build failed, exiting."; exit 1; }
  - ./buildmini.sh || { echo "Build failed, exiting."; exit 1; }
  - ./buildso.sh || { echo "Build failed, exiting."; exit 1; }
  - ./build3rdparty.sh || { echo "Build failed, exiting."; exit 1; }
  - ./copyserverfiles.sh || { echo "Build failed, exiting."; exit 1; }
  - ./copyclientfiles.sh || { echo "Build failed, exiting."; exit 1; }
  - ./buildtarballs.sh || { echo "Build failed, exiting."; exit 1; }
  - ./buildubuntu.sh || { echo "Build failed, exiting."; exit 1; }

