---
language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip build-essential git libx11-dev libxt-dev libraw1394-dev libavc1394-dev libiec61883-dev libfreetype6-dev yasm autoconf libtool openjdk-7-jdk libfaac0 libaudio-dev libpulse-dev libasound-dev
jdk:
  - openjdk7
script:
  - export JDK_HOME=$JAVA_HOME
  - cd build
  - ./buildsage.sh
  - ./buildmini.sh
  - ./buildso.sh
  - ./build3rdparty.sh
  - ./copyserverfiles.sh
  - ./copyclientfiles.sh
  - ./buildtarballs.sh
  - ./buildubuntu.sh
deploy:
  provider: bintray
  file: "build/binfiles.publish"
  user: $bintray_user
  key: $bintray_key
  dry-run: true
